---
title: "Lab 7"
date: "`r Sys.Date()`"
output:
  rmdformats::html_clean:
    highlight: kate
---


```{r setup, include=FALSE}
library(knitr)
library(rmdformats)

## Global options
options(max.print="75")
opts_chunk$set(echo=TRUE,
	             cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=75)
```

```{r}
# https://github.com/otakaran/twelvedays
library(twelvedays)
xmas2 <- read.csv("https://www.dropbox.com/s/ap2hqssese1ki4j/xmas_2.csv?dl=1")
```

```{r}
xmas2 <- xmas2 %>%
  mutate(Full.Phrase = pmap(list(num=Day, 
                                 num_word=Day.in.Words, 
                                 item=Gift.Item, 
                                 verb=Verb, 
                                 adjective=Adjective, 
                                 location=Location), 
                            make_phrase))

#apply(xmas2, 1:10, Full.Phrase, sing_day)

```

```{r}
lapply(1:12, sing_day, dataset = xmas2, phrase_col = Full.Phrase) %>%
  str_c(collapse = "\n\n") %>%
  str_glue()
```

```{r}
sing_dayz <- function(dataset, line, phrase_col) {
  stopifnot(is.data.frame(dataset))
  stopifnot(is.numeric(line))
  stopifnot(line > 0 & line <= length(row.names(dataset)))

  phrases <- dataset %>% pull({{phrase_col}})

  ret_string = str_glue("On the ", dataset[line, 2], " day of Christmas, my true love sent to me,")

  if (line == 1) {
    # We have to modify the phrase for line one if it is by itself
    phrase = str_replace(phrases[1], "and ", "")
    ret_string <- str_glue(ret_string, phrase, .sep = "\n")
  }
  else {
    phrases <- rev(phrases[1:line])
    ret_string <- str_glue(ret_string, paste(phrases, collapse = ",\n"), .sep = "\n")
  }
  ret_string <- str_glue(ret_string, ".")
  return(ret_string)
}
```


```{r}
sing_all_untill_day(xmas2, 12, Full.Phrase)
```





















